### PR TITLE
Use base64 encoding for exec() binary safe output when deriving share…

### PR DESCRIPTION
**Pull request by sun0x0001**
…d key (may contain CR/LF, etc)

### CODE REVIEW

**Comment by costyoancea** [comment]
@sun0x0001 : why not use trim?

**Comment by sun0x0001** [comment]
Hi! Because CR/LF may be contained inside the key, splitting it into several lines in $execOutput variable, but only $execOutput[0] used.

**Comment by costyoancea** [comment]
pipeline need to be green

**Comment by dsizov** [comment]
Hi @trydocatch , why this PR was not merged? Problem still exists for some apple pay tokens, because of line breaks in the output.

**Comment by trydocatch** [comment]
Issue confirmed

**Comment by trydocatch** [comment]
@sun0x0001 Thank you for the fix! We merged it, with some extra improvements.

**Pull request merged**
